# Generated by Django 3.2.18 on 2023-03-11 13:27

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to=books.models.get_path_img, verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Аннотация к книге')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('subgenre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.subgenre', verbose_name='Жанр')),
            ],
        ),
    ]
