# Generated by Django 3.2.18 on 2023-03-21 05:25

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='/nophotos.png', upload_to=books.models.get_path_img, verbose_name='Изображение'),
        ),
    ]
