# Generated by Django 3.2.18 on 2023-03-21 07:32

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(default=1, to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='nophoto.png', upload_to=books.models.get_path_img, verbose_name='Изображение'),
        ),
    ]
